name: workflow

on:
  push:
    branches: [ "master" ]

jobs:
  integratiion:
    name: Continuous integratiion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

