name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integratiion:
    name: Continuous integratiion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        uses: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

